### PR TITLE
Add extra param to purge

### PR DESCRIPTION
**Pull request by IgorWolbers**
# Change
I have added a `rclone-purge-args` argument that will be passed directly to the `rclone delete` command used to purge video files. 

# Use Case
The use case was the need to immediate deletion files on destinations where the file might otherwise go to a recycle bin by default. In my case I have a 7 day retention but the recycle bin in my destination does not purge until the file is 30 days old. This caused by device to run out of space.

# Caution
This is my first-time writing code in Python! I also have no idea how to compile or run the code as I have been using your Docker file by default. I am not new to coding (started writing c# in 2002) but I am new to Python. Please do not accept this PR without vetting my code. I did try to follow along with the process in `CONTRIBUTING.md` but I could not get the application to run in my Windows environment from the poetry shell.

# Other
I did follow your syntax, styles, etc. If there are any changes you want to make please feel free, I will not be offended at all. Thanks again for a great project and sharing/maintaining it as a public repo!

### CODE REVIEW

**Comment by ep1cman** [comment]
Thanks for the pull request! I had no idea such a thing existed and this is a very nice way to handle it. The code all looks good to me, the only thing I would request is that you dont add the argument to the dockerfile. In fact I might need to go in and clean those up because they are not all required (or a lot of them are missing if I want them all there)

I shall give it a test and if it runs fine (which I don't see why it wouldn't) I will merge once the above change is made.

**Comment by IgorWolbers** [comment]
> ... the only thing I would request is that you dont add the argument to the dockerfile. 

Thanks, I will keep this in mind going forward. Thanks again and also sorry again I did not actually run the code change I made.

**Comment by ep1cman** [comment]
Sorry it took me a while, I just tested this and it works as expected. A new release will be done with this feature shortly

**Comment by IgorWolbers** [comment]
No worries and thank you so much for doing this! I plan on deploying the new version this weekend.

**Pull request merged**
