### PR TITLE
Switch to using UIProtect library

### PR DESCRIPTION
**Pull request by LloydPickering**
With Unifi OS 4.0.3 I can't get the existing container to connect using either latest or dev branch (both with and without experimental downloader flag). I am using a valid SSL Cert too, so that's not an issue (with SSL Verify both on and off).

With latest I get AttributeError: 'NoneType' object has no attribute 'split' (in cookies)
With dev I get /proxy/protect/api/bootstrap - Status: 401 - Reason: {'code': 401, 'message': 'Unauthorized'}

I have tested the latest HomeAssistant Unifi Protect plugin which has recently switched to using UIProtect library and that connects fine to unifi, so it has to be an issue that still remains in the auth of pyunifiprotect, hence the attempt to upgrade.

I'm not a python dev and I'm Windows based so have taken this as far as I can, but this PR looks about 95% correct I think. I note it needs to use Python 3.10.

Doing a 'docker build .' gives lots of ': No such file or directory bash' but I'm pretty sure it would be an easy fix for someone who knows python, it's tooling and the existing codebase.

I'd do more to sort this but I'm a bit worn out. I'm trying to take live offsite backups of CCTV for a building right next door to a mosque where we have been given police intelligence it's likely to be targeted this evening by riots. Hopefully nothing happens as I've spent all day trying to get offsite backups working but I have failed meaning I won't have any CCTV if things do kick off. Fingers Crossed.

### CODE REVIEW

**Comment by ep1cman** [comment]
Hi,

So sorry to hear about the riots here in the UK affecting you, truly is shameful what they are doing.

Could you please open an issue to track the problem you are having separate to this? 

I'm afraid the switch to uiprotect has been hung up on a PR to add the new experimental downloader. Unfortunately none of us involved have had the time to get that PR over the line. I think what I will do is roll back that feature and make the upgrade without it.

**Comment by Sticklyman1936** [comment]
FWIW, regarding the initial issue: I am using Unifi OS 4.0.12 w/ Protect 4.0.33 with the `latest` tag of the docker container without issues. It might be worth trying to upgrade. (Sorry, I know that this comment should be on an issue, but mentioning it here in case it helps for tonight. I hope the riots don't materialise tonight!)

**Comment by LloydPickering** [comment]
@ep1cman and @Sticklyman1936 thanks for the support. I have opened issue #161 to track the actual issue instead of solutionising here.

So far my community building is safe and I have partially managed to get it working by hooking up the RTSP fields on the external facing cameras to an ffmpeg dump so if something does happen at least I should get video of those involved. It's not an ideal solution though as it records everything rather than just motion or people so it's a temp workaround for the immediate crisis.

**Comment by ep1cman** [comment]
Thanks for this PR, I've tested this and suprisingly things seem to be working smoothly out of the box. I was expecting some level of breaking changes but it looks like we got lucky.

I have one question, why were dev/test dependencies made non optional? These really shouldn't be installed by anyone except people developing this tool

**Comment by LloydPickering** [comment]
It might be my lack of knowledge of the dev tooling, but whenever I ran 'poetry install -E dev' or for -E test it couldn't find any dependencies. I think in newer versions of poetry the config for setting up optional groupings is probably different. I brute forced a fix by making them required so they installed correctly (for me). Someone who knows poetry better would probably be able to migrate to a newer config format that is understood by the tooling.

**Comment by ep1cman** [comment]
if you could undo that I will look into it and update as needed. I suspect I just need to change the command to run in the cotribution guide. In general that document needs some love

**Comment by LloydPickering** [comment]
I've reverted the dev/test optional code now

**Pull request merged**
