### PR TITLE
Adding support for SMART_DETECT_LINE events

### LINKED ISSUE #69: Add support for line crossing events
Unifi protect at some point added "Line crossing" events that are separate from motion or smart detect events. This tool should handle those too.

### PR DESCRIPTION
**Pull request by jimmydoh**
Adjusting the types to include support for SMART_DETECT_LINE.

Closes #69 

Could similarly add support for Audio detections, Smart Detect animals, etc. in the future but the DETECTION_TYPES parameter could become unwieldly.

Tested with:
Python 3.12.6
UnifiOS 4.0.6
Protect 4.1.53

NOTE: This will often result in duplicate or very similar events being uploaded as Protect can trigger as both a Smart Detect Zone and Smart Detect Line event at the same time, depending on your settings.

e.g. a Person crosses a Line and there is also an active Smart Detect Zone setup at the same location.

### CODE REVIEW

**Comment by jimmydoh** [comment]
Requires patching of the uiprotect library first - currently does not get returned as a Device event (event.type.value in EventType.device_events_set()).

**Comment by ep1cman** [comment]
Thanks for this! Its been a long lingering to do so it will be great to get that closed off

**Comment by JonLaliberte** [comment]
Looks like this was added in v6.1.0 of the uiprotect library. Can this be merged into unifi-protect-backup now?

**Comment by ep1cman** [comment]
I've reopened this pull request. Are you able to also bump the version of ui protect used as part of this or?

**Pull request merged**
